# https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name: install dependencies (& java jdk)
  become: yes
  apt: name={{ dependencies }} update_cache=yes cache_valid_time=3600 state=present
