---
apache_repository: false
apache_install:
  - apache2
  - git

apache_module_disable: false
apache_module_enable:
  - rewrite
  - ssl

apt_packages_php:
  - php{{ php_version}}
  - php{{ php_version}}-cli
  - php{{ php_version}}-mysql
  - php{{ php_version}}-common
  - php{{ php_version}}-curl
  - php{{ php_version}}-gd
  - php{{ php_version}}-gmp
  - php{{ php_version}}-json
  - php{{ php_version}}-intl
  - php{{ php_version}}-ldap
  - php{{ php_version}}-mcrypt
  - php{{ php_version}}-sqlite3
  - php{{ php_version}}-xsl
  - php{{ php_version}}-sybase
  - php{{ php_version}}-odbc
  - php{{ php_version}}-imap
  - php{{ php_version}}-dev
  - php{{ php_version}}-bcmath
  - php{{ php_version}}-mbstring
  - php{{ php_version}}-soap
  - php{{ php_version}}-zip

php_version: 7.1
http_port: 80
